name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install fpm
        run: curl https://get.fpm.org | sh

      - name: Build program
        run: fpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: program
          path: bin/program
