name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install gfortran

    - name: Build program
      run: |
        gfortran -o program ./src/mrna_sync.f90

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: program
